import {
  CreateSecretCommand,
  DeleteSecretCommand,
  DescribeSecretCommand,
  GetSecretValueCommand,
  ResourceNotFoundException,
  SecretsManagerClient,
  UpdateSecretCommand,
} from '@aws-sdk/client-secrets-manager';
import { Aws } from '/opt/nodejs/aws/constants';
import { OCPICredentialRole } from '/opt/nodejs/modules/ocpi-credentials/ocpi-credentials.model';

const secretsClient = new SecretsManagerClient({ region: Aws.region });

/**
 * The secret value stored per OCPI party in AWS Secrets Manager.
 * - CREDENTIALS_TOKEN_B: the token the party sent us during the credentials handshake
 * - CREDENTIALS_TOKEN_C: the new token we generated and returned to the party
 */
export interface OCPIPartySecretValue {
  CREDENTIALS_TOKEN_B: string;
  CREDENTIALS_TOKEN_C: string;
}

/**
 * Loads the stored OCPI party secret from AWS Secrets Manager.
 *
 * The secret contains both token directions:
 * - CREDENTIALS_TOKEN_B: token provided by the remote party
 * - CREDENTIALS_TOKEN_C: token generated by BFE and returned to the party
 */
export const getPartySecret = async (
    secretRef: string,
): Promise<OCPIPartySecretValue | null> => {
  try {
    const response = await secretsClient.send(
        new GetSecretValueCommand({
          SecretId: secretRef,
        }),
    );

    if (!response.SecretString) {
      return null;
    }

    return JSON.parse(response.SecretString) as OCPIPartySecretValue;
  } catch (err) {
    if (err instanceof ResourceNotFoundException) {
      return null;
    }

    throw err;
  }
};

/**
 * Persists both OCPI tokens for a party as a new secret in AWS Secrets Manager.
 *
 * The secret is stored under a deterministic path based on the party's role,
 * country code, and party ID, e.g.: /emobility/ocpi/parties/CPO/CH/XYZ
 *
 * This function is only called once per party during the initial credentials
 * handshake. Re-registration is prevented upstream by invalidating the
 * bootstrap token after first use.
 *
 * @param role    - The OCPI role of the party (CPO, EMSP, etc.)
 * @param tokenB  - Credentials Token B (received from CPO)
 * @param tokenC  - Credentials Token C (generated by eMSP)
 * @returns The secret name (path), which is stored as a reference in DynamoDB
 *          instead of the plaintext token
 */
export const savePartySecret = async (
  role: OCPICredentialRole,
  tokenB: string,
  tokenC: string,
): Promise<string> => {
  const secretName = `/emobility/ocpi/parties/${role.role}/${role.country_code}/${role.party_id}`;
  const secretValue: OCPIPartySecretValue = {
    CREDENTIALS_TOKEN_B: tokenB,
    CREDENTIALS_TOKEN_C: tokenC,
  };
  const secretString = JSON.stringify(secretValue);

  await secretsClient.send(
    new CreateSecretCommand({
      Name: secretName,
      SecretString: secretString,
    }),
  );

  // Return the secret name so it can be stored as a reference in DynamoDB
  return secretName;
};

export const partySecretExists = async (role: OCPICredentialRole): Promise<boolean> => {
  const secretName = `/emobility/ocpi/parties/${role.role}/${role.country_code}/${role.party_id}`;
  try {
    await secretsClient.send(new DescribeSecretCommand({ SecretId: secretName }));
    return true;
  } catch (err) {
    if (err instanceof ResourceNotFoundException) {return false;}
    throw err;
  }
};

/**
 * Updates the stored OCPI token pair for an already registered party.
 *
 * TOKEN_B is provided by the remote party.
 * TOKEN_C is generated by BFE and returned to the remote party.
 */
export const updatePartySecret = async (
    secretRef: string,
    tokenB: string,
    tokenC: string,
): Promise<void> => {
  const secretValue: OCPIPartySecretValue = {
    CREDENTIALS_TOKEN_B: tokenB,
    CREDENTIALS_TOKEN_C: tokenC,
  };

  await secretsClient.send(
      new UpdateSecretCommand({
        SecretId: secretRef,
        SecretString: JSON.stringify(secretValue),
      }),
  );
};

/**
 * Deletes the stored OCPI party secret from AWS Secrets Manager.
 *
 * This is used when an existing OCPI credentials connection is terminated.
 */
export const deletePartySecret = async (secretRef: string): Promise<void> => {
  try {
    await secretsClient.send(
        new DeleteSecretCommand({
          SecretId: secretRef,
          // Immediately deletes the secret without a recovery window to fully terminate the OCPI connection
          ForceDeleteWithoutRecovery: true,
        }),
    );
  } catch (err) {
    if (err instanceof ResourceNotFoundException) {
      return;
    }

    throw err;
  }
};
